// src/texts.rs

#[derive(Debug)]
pub struct Texts {
    pub description: &'static str,
    pub epilog: &'static str,
    pub source_crs_help: &'static str,
    pub target_crs_help: &'static str,
    pub coords_help: &'static str,
    pub input_file_help: &'static str,
    pub output_file_help: &'static str,
    pub error_crs_creation: &'static str,
    pub error_proj: &'static str,
    pub error_single_coords_missing: &'static str,
    pub transform_result: &'static str,
    pub file_transform_complete: &'static str,
    pub warning_skip_row: &'static str,
    pub error_input_not_found: &'static str,
    pub error_output_creation: &'static str,
    pub error_invalid_coordinate: &'static str,
    pub reason: &'static str,
    pub single_about: &'static str,
    pub file_about: &'static str,
}

pub fn get_texts(lang_code: &str) -> Texts {
    match lang_code {
        "en" => Texts {
            description: "A powerful coordinate transformation tool using the 'proj' crate to convert between different Coordinate Reference Systems (CRS).",
            epilog: "Usage Examples:\n\n1. Transform a single point (WGS84 lat/lon -> WGS84 / UTM zone 51N):\n   xyz2lat single --source-crs EPSG:4326 --target-crs EPSG:32651 --coords 121.5654 25.0330\n\n2. Batch transform from a file (Beijing 1954 / 3-degree Gauss-Kruger zone 40 -> WGS84):\n   xyz2lat file --source-crs EPSG:2436 --target-crs EPSG:4326 --input-file input.csv --output-file output.csv\n\n3. Transform using a PROJ string:\n   xyz2lat single --source-crs \"EPSG:4326\" --target-crs \"+proj=utm +zone=51 +datum=WGS84\" --coords 121.56 25.03",
            source_crs_help: "Define the source CRS. Can be an EPSG code (e.g., 'EPSG:4326') or a PROJ string.\nFind EPSG codes at https://epsg.io/",
            target_crs_help: "Define the target CRS. Can be an EPSG code (e.g., 'EPSG:32651') or a PROJ string.\nFind EPSG codes at https://epsg.io/",
            coords_help: "In 'single' mode, the coordinates to be transformed. Accepts 2 values (x y), separated by spaces.",
            input_file_help: "In 'file' mode, the path to the input CSV file. The first row should be a header.",
            output_file_help: "In 'file' mode, the path to the output CSV file to save results.",
            error_crs_creation: "Error: Failed to create Coordinate Reference System.",
            error_proj: "PROJ Error",
            error_single_coords_missing: "Error: In 'single' mode, you must provide 2 coordinate values using --coords.",
            transform_result: "Transformation Result",
            file_transform_complete: "File transformation complete! Results saved to",
            warning_skip_row: "Warning: Skipping malformed row",
            error_input_not_found: "Error: Input file not found",
            error_output_creation: "Error: Could not create output file",
            error_invalid_coordinate: "Invalid coordinate value",
            reason: "Reason",
            single_about: "Transform a single coordinate point.",
            file_about: "Batch transform coordinates from a file.",
        },
        _ => Texts {
            description: "一个功能强大的坐标转换工具，使用 `proj` 库在不同的坐标参考系统 (CRS) 之间进行转换。",
            epilog: "使用示例:\n\n1. 转换单个坐标点 (WGS84 经纬度 -> WGS84 / UTM zone 51N):\n   xyz2lat single --source-crs EPSG:4326 --target-crs EPSG:32651 --coords 121.5654 25.0330\n\n2. 从文件批量转换 (北京 1954 / 3-degree Gauss-Kruger zone 40 -> WGS84):\n   xyz2lat file --source-crs EPSG:2436 --target-crs EPSG:4326 --input-file input.csv --output-file output.csv\n\n3. 使用 PROJ 字符串进行转换:\n   xyz2lat single --source-crs \"EPSG:4326\" --target-crs \"+proj=utm +zone=51 +datum=WGS84\" --coords 121.56 25.03",
            source_crs_help: "定义源坐标参考系统。可以是 EPSG 代码 (如 'EPSG:4326') 或 PROJ 字符串。\n您可以在 https://epsg.io/ 网站上查找 EPSG 代码。",
            target_crs_help: "定义目标坐标参考系统。可以是 EPSG 代码 (如 'EPSG:32651') 或 PROJ 字符串。\n您可以在 https://epsg.io/ 网站上查找 EPSG 代码。",
            coords_help: "在 'single' 模式下，提供要转换的坐标。接受2个值 (x y)，用空格分隔。",
            input_file_help: "在 'file' 模式下，指定包含源坐标的输入CSV文件路径。文件第一行应为表头。",
            output_file_help: "在 'file' 模式下，指定用于保存转换结果的输出CSV文件路径。",
            error_crs_creation: "错误：无法创建坐标参考系统。",
            error_proj: "PROJ 错误",
            error_single_coords_missing: "错误: 在 'single' 模式下, 必须使用 --coords 提供2个坐标值。",
            transform_result: "转换结果",
            file_transform_complete: "文件转换完成！结果已保存至",
            warning_skip_row: "警告：跳过格式错误的行",
            error_input_not_found: "错误：输入文件未找到",
            error_output_creation: "错误：无法创建输出文件",
            error_invalid_coordinate: "无效的坐标值",
            reason: "原因",
            single_about: "转换单个坐标点",
            file_about: "从文件批量转换坐标",
        },
    }
}
